import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useRef, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [feedbackItems, setFeedbackItems] = useState<
    { id: string; email: string; text: string }[]
  >([]);

  const emailInputRef = useRef<HTMLInputElement>(null);
  const feedbackInputRef = useRef<HTMLTextAreaElement>(null);

  const submitFormHandler = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const enteredEmail = emailInputRef.current?.value;
    const enteredFeedback = feedbackInputRef.current?.value;

    const reqBody = { email: enteredEmail, feedback: enteredFeedback };

    const res = await fetch("/api/feedback", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(reqBody),
    });
    const data = await res.json();
    console.log(data);
  };

  async function loadFeedbackHandler() {
    const res = await fetch("/api/feedback");
    const data = await res.json();
    setFeedbackItems(() => data.feedback);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home Page</h1>

        <form onSubmit={submitFormHandler}>
          <div>
            <label htmlFor="email">Your Email Address</label>
            <input type="email" id="email" ref={emailInputRef} />
          </div>

          <div>
            <label htmlFor="email">Your Email Feedback</label>
            <textarea id="feedback" rows={5} ref={feedbackInputRef}></textarea>
          </div>

          <button>Send Feedback</button>
        </form>

        <button onClick={loadFeedbackHandler}>Load Feedback</button>

        <ul>
          {feedbackItems.map((item) => (
            <li key={item.id}>{item.text}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
